name: apk_test
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  dio: ^5.8.0+1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  jiffy: ^6.3.2
  permission_handler: ^11.4.0
  pkce: ^1.1.0+1
  path_provider: ^2.1.5
  pinput: ^5.0.1
  rxdart: ^0.27.7
  fl_chart: ^0.63.0  
  build_config: ^1.2.0
  lehttp_overrides: ^1.0.3
  synchronized: ^3.4.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.1.6
  http:
  font_awesome_flutter: ^10.6.0
  bloc: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
